config/routes.rb
LandmarkApp::Application.routes.draw do
  
  root :to => 'landmarks#index'
  
  get "/landmarks" => 'landmarks#index', :as => :landmarks

  get "/landmarks/new" => 'landmarks#new', :as => :new_landmark
  
  get "landmarks/:id" => 'landmarks#show', :as => :landmark
  put "landmarks/:id" => 'landmarks#update', :as => :landmark
  delete "landmarks/:id" => 'landmarks#destroy', :as => :landmark
  
  get "landmarks/:id/edit" => 'landmarks#edit', :as => :edit_landmark

  post "/landmarks" => 'landmarks#create'

  

end

app/models/landmark.rb
class Landmark < ActiveRecord::Base
  
  validates :name, :presence => true, :uniqueness => true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController
  
  def index
    @landmarks = Landmark.order("name asc")
  end

  def show
    @landmark = Landmark.find_by_id(params[:id])
  end

  def destroy
    @landmark = Landmark.find_by_id(params[:id])
    @landmark.destroy
    redirect_to landmarks_url
  end

  def edit
    @landmark = Landmark.find_by_id(params[:id])
  end

  def update
    @landmark = Landmark.find_by_id(params[:id])
    if @landmark.update_attributes(params[:landmark])
      redirect_to landmark_url(@landmark.id)
    else
      render :action => 'edit'
    end
  end


  def new
    @landmark = Landmark.new
  end

  def create
    @landmark = Landmark.new(params[:landmark])
    if @landmark.save
      redirect_to landmarks_url
    else
      render :action => 'new'
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landmarks/_form.html.erb
<table>
<%= form_for @landmark do |form| %>
	<tr>
	<td> <%= form.label :name %> </td>
	<td> <%= form.text_field :name %> </td>
	</tr>
	<tr>
	<td> <%= form.label :address %> </td>
	<td> <%= form.text_area :address, :rows => 3 %> </td>
	</tr>
	<tr>
	<td> <%= form.label :primary_use, text='Why Bother?' %> </td>
	<td> <%= form.text_area :primary_use, :rows => 3 %> </td>
	</tr>
	<tr>
</table>

<br>
<br>

<%= link_to "Cancel", landmarks_url %> | <%= form.submit %> 



<% end %>

app/views/landmarks/edit.html.erb
<h1><%= @landmark.name %></h1>
<br>
<%= render 'landmarks/form' %>

app/views/landmarks/index.html.erb
<h1>Detroit Landmarks</h1>

	<% label = 0 %>
	<% markers = "" %>
	
	<% @landmarks.each do |landmark| %>
		
		<% if landmark.address != "" %>
			<% label = label + 1 %>
			<p> <%= link_to landmark.name, landmark_url(landmark.id)  %> (<%= label%>)</p>
			<% markers = markers + "&" + "markers=color:blue|label:#{label}|#{landmark.address}" %>
			
		<% else %>
			<p> <%= link_to landmark.name, landmark_url(landmark.id)  %></p>
		<% end %>
		
	<% end %>
		
		<br>
		
	<%= link_to "Add a New Landmark", new_landmark_url %>
	
<p><img border="0" src="http://maps.googleapis.com/maps/api/staticmap?center=Dearborn, MI&zoom=9&size=640x400&sensor=false&<%= markers %>" alt="Trip to Detroit" /></p>

app/views/landmarks/new.html.erb
<h1> Add a New Detroit Landmark </h1>

<%= render 'landmarks/form' %>

app/views/landmarks/show.html.erb
<h1><%= @landmark.name%></h1>


<p><b>Address:</b> <%= @landmark.address%></p>
<p><b>Why Bother:</b> <%= @landmark.primary_use%></p>

<br>

<%= link_to "Edit Landmark", edit_landmark_url(@landmark.id) %> | <%= link_to "Delete", landmark_url(@landmark.id), :confirm => 'Are you sure?', :method => :delete %> | <%= link_to "View All Landmarks", landmarks_url %>

<br>

<% if @landmark.address != "" %>
<p><img border="0" src="http://maps.googleapis.com/maps/api/staticmap?center= <%= @landmark.address %>&zoom=13&size=400x400&sensor=false&markers=color:blue|<%= @landmark.address %>" alt="<%= @landmark.address%>" /></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LandmarkApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>